name: CI

on:
  push: ~
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup DMD
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-2.100.2

    - name: Build executable
      run: |
        dub build
